language: perl
perl:
  - "5.26"
before_script:
  - cpanm --quiet --notest --skip-satisfied Devel::Cover Devel::Cover::Report::Codecov
script:
  - perl Makefile.PL
  - make
  - cover -test
after_success:
  - cover -report codecov
deploy:
  provider: heroku
  buildpack: http://github.com/judofyr/perloku.git
  api_key: 29550f03-12ca-4098-a4c2-6354c7ee0c0f
  app: robertleap
  on:
    all_branches: true
