name: Perl CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: check Perl version
      run: perl -v
    - name: install cpanm
      run: curl -L https://cpanmin.us | sudo perl - App::cpanminus
    - name: check cpanm version
      run:  cpanm --version
    - name: install Devel Cover
      run:  cpanm --quiet --notest --skip-satisfied Devel::Cover Devel::Cover::Report::Codecov
    - name: build and test
      run: |
        perl Makefile.PL
        make
        cover -test
    - name: create coverage report
      run: cover -report codecov
