name: robert_leap

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Check Perl version
      run: perl --version
    - name: before_script
      run: cpanm -version
