name: Perl CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Check Perl version
      run: perl -v
    - name: before_script
      run: |
        curl -L https://cpanmin.us | perl - App::cpanminus
        cpanm -v
        cpanm --quiet --notest --skip-satisfied Devel::Cover Devel::Cover::Report::Codecov
    - name: script
      run: |
        perl Makefile.PL
        make
        cover -test
    - name: after_success
      run: cover -report codecov
